### ISSUE TITLE
Need Firebase authentication in the backend

### ISSUE THREAD

**Issue by nehakalbande** [nehakalbande/Vision-Voice-Test#11]

**Comment by PriyanshX1902** [comment]
@nehakalbande Could you assign me to it :)?

**Comment by ArielSav** [comment]
Would love to help :)

**Comment by nehakalbande** [comment]
Yes sure @PriyanshX1902 Go ahead! Assigning to you.

**Comment by nehakalbande** [comment]
@ArielSav after firebase authentication, will be adding more issues. Please contribute to it :)

**Comment by nehakalbande** [comment]
@PriyanshX1902 Please connect on discord for Firebase project neha_kalbande#0153

**Comment by PriyanshX1902** [comment]
@nehakalbande I am unable to find you on discord using the id that you have provided, you can connect with me at ArjunX#3457 .
