### ISSUE TITLE
 RESULT PAGE DESIGN

### ISSUE THREAD

**Issue by nehakalbande** [nehakalbande/Vision-Voice-Test#18]

**Comment by rajputarjun2001** [comment]
Hi @nehakalbande I want to work on this issue, could you please assign this to me?

**Comment by nehakalbande** [comment]
Yes sure @rajputarjun2001 Assigning to you 
Please connect on discord, to discuss about the design. 
![hh](https://user-images.githubusercontent.com/65285162/135516128-48ad824d-170b-4e0a-885a-6acc4448694e.jpg)
