### ISSUE TITLE
Adding google auth in the backend

### ISSUE THREAD

**Issue by nehakalbande** [nehakalbande/Vision-Voice-Test#2]

**Comment by Jisan129** [comment]
Can I work on this?

**Comment by AyoubBoulahtar** [comment]
Hello, can I help ?

**Comment by Jisan129** [comment]
I want to work in this feature
But never implemented Google Auth before .
Can I give it a try?

**Comment by PriyanshX1902** [comment]
We can use Firebase Authentication to do so.

**Comment by nehakalbande** [comment]
Yes @PriyanshX1902 firebase authentication can also help, if you can do let us know.

**Comment by nehakalbande** [comment]
Hi @AyoubBoulahtar will you be able to do google auth ?

**Comment by PriyanshX1902** [comment]
Sure, I can implement it. We can also use firebase realtime database to store a user's past results.

**Comment by nehakalbande** [comment]
Correct! Ok then go ahead @PriyanshX1902 Will create a issue for it and do comment on that firebase issue. 
- After authentication, logout button should also appear in the navbar

**Comment by nehakalbande** [comment]
@AyoubBoulahtar Please see other issues as well for backend part. Will be able to assign you then.

**Comment by AyoubBoulahtar** [comment]
@PriyanshX1902 i'll be available for any help ..

**Comment by PriyanshX1902** [comment]
@AyoubBoulahtar Sure, I'll ping you
