### ISSUE TITLE
Improving the navigation bar by adding animations

### ISSUE THREAD

**Issue by developer-ishan** [nehakalbande/Vision-Voice-Test#25]
I want to work on it as part of Hacktoberfest.

**Comment by nehakalbande** [comment]
@developer-ishan What type of animations you want to add?

**Comment by developer-ishan** [comment]
The navbar pops up instantly when opened in mobile view. It would look great if it appears smoothly.

**Comment by nehakalbande** [comment]
Its not needed @developer-ishan :)
