### ISSUE TITLE
Make Dropdown properly aligned

### ISSUE THREAD

**Issue by PriyanshX1902** [nehakalbande/Vision-Voice-Test#28]
![image](https://user-images.githubusercontent.com/72353221/135740004-72e40b96-7a74-4551-ba79-f6b8ea63129b.png)
Align it with Username, Also add a dropdown icon to the right  of  Hi {Username}.

**Comment by RamanChola** [comment]
Hi, i would like to work on this.

**Comment by PriyanshX1902** [comment]
@nehakalbande

**Comment by nehakalbande** [comment]
@PriyanshX1902 i am adding this issue with #7 
Both issues are of Alignment so merging into one. You can work on it then.

**Comment by PriyanshX1902** [comment]
@RamanChola comment on issue #7, I am busy with another issue.
