### ISSUE TITLE
Add Animations in Vision and Aural paragraph

### ISSUE THREAD

**Issue by ruchika-01p** [nehakalbande/Vision-Voice-Test#3]

**Comment by priyanka010392** [comment]
@ruchika-01p can you assign this to me? Also, to clarify - need animation for the green color images right?

**Comment by ruchika-01p** [comment]
Yes sure, assigning to you.
You have to put animations to the both green colored images and also to the paragraphs besides the images.

**Comment by priyanka010392** [comment]
> Yes sure, assigning to you.
> You have to put animations to the both green colored images and also to the paragraphs besides the images.

Working on it, will raise pr during Hacktober fest
