### ISSUE TITLE
All the links should be aligned horizontally and ABOUT should be put below them then it will look nice.

### ISSUE THREAD

**Issue by AnuragRoshan** [nehakalbande/Vision-Voice-Test#36]

**Comment by nehakalbande** [comment]
Can you put a ss. What are you talking about?

**Comment by AnuragRoshan** [comment]
![Screenshot 2021-10-04 153929](https://user-images.githubusercontent.com/68966298/135833271-dfecad5e-196c-4674-8c8c-c5688788975b.jpg)
Link should Be aligned horizontally , About should be put below them and Hover on link and about shows underline which looks ugly

**Comment by nehakalbande** [comment]
There is already an issue added of footer alignment :)
