### ISSUE TITLE
Instead of using textual email and phone number you should use mail and phone icon and link that with your email and phone number repectively so users can easily call or mail you .

### ISSUE THREAD

**Issue by AnuragRoshan** [nehakalbande/Vision-Voice-Test#37]
![Screenshot 2021-10-04 154403](https://user-images.githubusercontent.com/68966298/135833867-61d34a3d-3429-4870-b039-02f74e547a35.jpg)
use phone and mail icon and link it so user need not use copy

**Comment by nehakalbande** [comment]
We dont have any email or phone no as of now.
Its just for a temporary purpose

**Comment by AnuragRoshan** [comment]
adding icons makes it more attractive

**Comment by nehakalbande** [comment]
@AnuragRoshan Yes, You can modify the contact page :)
