### ISSUE TITLE
Make Footer Mobile Responsive

### ISSUE THREAD

**Issue by nehakalbande** [nehakalbande/Vision-Voice-Test#44]
Remove the white space below the footer ( appearing in some pages) and Scroll Bar is also appearing

![Screenshot (75)](https://user-images.githubusercontent.com/65285162/136262311-e2f9555d-0875-4f73-8650-80cc735db1e9.png)

**Comment by ANAND-NARAYAN-JHA** [comment]
Assign me i will do it @nehakalbande

**Comment by nehakalbande** [comment]
Assigning @ANAND-NARAYAN-JHA

**Comment by nehakalbande** [comment]
@ANAND-NARAYAN-JHA any updates?
