### ISSUE TITLE
Make all links open in new tab

### ISSUE THREAD

**Issue by ruchika-01p** [nehakalbande/Vision-Voice-Test#5]

**Comment by rahulbhatt1899** [comment]
Hey, could you provide more information on this, I would like to contribute!

**Comment by nehakalbande** [comment]
Hi, make all the links in the website to open on a new tab.
For ex: by clicking on aural test, the test page should open on a new tab

**Comment by rahulbhatt1899** [comment]
Alright, could you assign this issue to me?

**Comment by nehakalbande** [comment]
Yeah sure! Work on it

**Comment by nehakalbande** [comment]
Please make a PR once done.

**Comment by paltannistha** [comment]
Hey I want to work on this. But I am new to open source. Can u please guide me how to contribute?

**Comment by nehakalbande** [comment]
Hi @paltannistha this issue got resolved, please have a look on other issues as well to work on.

**Comment by paltannistha** [comment]
@nehakalbande okay thank you.
