### ISSUE TITLE
Fetch The Data From Backend into Results Page

### ISSUE THREAD

**Issue by nehakalbande** [nehakalbande/Vision-Voice-Test#58]

**Comment by jashlodhavia** [comment]
Hey, Please assign it to me if the issue is still open

**Comment by nehakalbande** [comment]
Yes @jashlodhavia assigning to you,
Please fetch only the required data i.e., given on the results page

**Comment by jashlodhavia** [comment]
Hey, So sorry. I am busy with another project.

**Comment by fumblehool** [comment]
Hi, @nehakalbande I can work on this.
Please assign me the task

**Comment by nehakalbande** [comment]
@fumblehool  assigning to you,
Please make sure to fetch only the required data i.e., given on the results page
