### ISSUE TITLE
Work on Results Page

### ISSUE THREAD

**Issue by nehakalbande** [nehakalbande/Vision-Voice-Test#6]
Work on the results page so that it prints  result of 
- Vision
- Aural test in pdf format

**Comment by nehakalbande** [comment]
Hi @srijit2002
- Need to build database for vision and aural test.. Users will give the test and the data should get stored 
- Then People can download their results in the PDF format 
- Please let firebase authentication issue be resolved.. Someone is working on the authentication part.. 
- You can then proceed ahead.. Will assign it to you :) Works?

**Comment by nehakalbande** [comment]
Firebase Firestore database. 
MongoDb sometimes doesnt work quite well :) 
There is no community yet.. You can connect on discord 
![IMG_20210927_191607](https://user-images.githubusercontent.com/65285162/134921025-96dc0c8f-ad10-48b7-961b-fba0e13bfd2f.jpg)

**Comment by srijit2002** [comment]
@nehakalbande .Thanks for replying. 
>Please let firebase authentication issue be resolved.. Someone is working on the authentication part..

So I will wait until someone completes the firebase authentication

**Comment by srijit2002** [comment]
@nehakalbande can you please accept my friend request on discord,I need to discuss about this topic. My id is `Romanrijit`

**Comment by nehakalbande** [comment]
@srijit2002 Firebase authentication PR is merged. You can work on it now. Is it Fine?

**Comment by srijit2002** [comment]
@nehakalbande yup, I can but it will take some time

**Comment by nehakalbande** [comment]
No issue, But try to complete it asap. 
Will you work on this issue?

**Comment by srijit2002** [comment]
> No issue, But try to complete it asap. Will you work on this issue?

I will try my best to do it asap. Yup I will
